version: '3.4'

services:
  
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  orderdb:
    image: mcr.microsoft.com/mssql/server

  messagebroker:
    image: rabbitmq:management

  distributedcache:
    image: redis 

volumes:
  postgres_catalog:
  postgres_basket:  